from .required_fields_script_reading import RequiredFieldsScriptReading
from .script_reading_result_dto import ScriptReadingResultDTO
from .recording_related_fields_score import RecordingRelatedFieldsScore
from .quote_translation_result_dto import QuoteTranslationResultDTO
from .photo_interpretation_result_dto import PhotoInterpretationResultDTO
