from .RequiredFieldsScriptReading import RequiredFieldsScriptReading
from .ScriptReadingResultDTO import ScriptReadingResultDTO
from .RecordingRelatedFieldsScore import RecordingRelatedFieldsScore
from .QuoteTranslationResultDTO import QuoteTranslationResultDTO
from .PhotoInterpretationResultDTO import PhotoInterpretationResultDTO
